name: Deploy automático

on:
  workflow_run:
    workflows: ["API feita com DRF"]
    branches: [main]
    type:
      - completed

jobs:
  deploy_app:
    runs-on: ubuntu-latest
    steps:
      - name: Realiza o checkout
        uses: actions/checkout@v2

      - name: Deploy no Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "api-com-drf"
          heroku_email: "zicadopv@gmail.com"
